PORT: "8080"
FUNASR_ADDR: "localhost:8000"
REDIS_ADDR: "localhost:6379"
WORKER_POOL_SIZE: 10
MAX_CONNECTIONS: 2000
LOG_LEVEL: "info"
MAX_AUDIO_FILES_PER_USER: 10
DB_HOST: "localhost"
DB_PORT: 5432
DB_USER: "root"
DB_PASSWORD: "123456"
DB_NAME: "root"
